export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export type DomainName = "canvas" | "assets" | "image-workbench" | "video-workbench";
export const domainNames: DomainName[] = ["canvas", "assets", "image-workbench", "video-workbench"];
export const domainLabels: Record<DomainName, string> = { canvas: "画布", assets: "我的素材", "image-workbench": "图片生成记录", "video-workbench": "视频生成记录" };
export type MediaRef = { pointer: string; fileKey: string; representation: "blob-url" | "data-url" | "storage-key" };
export type Domain = { name: DomainName; domainVersion: 1; data: { [key: string]: Json }; mediaRefs: MediaRef[] };
export type ManifestFile = { fileKey: string; sha256: string; bytes: number; mimeType: string; originalStorageKey?: string };
export type Manifest = { app: "infinite-canvas"; manifestVersion: 1; clientId: string; capturedAt: string; domains: Domain[]; files: ManifestFile[] };
export type Media = { mediaId: string; sha256: string; bytes: number; mimeType: string };
export type Backup = { backupId: string; state: "draft" | "committed" | "deleted" | "cancelled"; manifest: Manifest | null; manifestSha256: string; mediaBindings: Media[]; missing: string[]; createdAt: string; committedAt: string | null };
export type BackupSummary = Pick<Backup, "backupId" | "createdAt" | "committedAt"> & { domains: { name: DomainName; records: number }[]; bytes: number };
export type CloudStatus = { serverId: string; workspaceId: string; apiVersion: number; policy: { maxFileBytes: number; maxJSONBytes: number; maxResolveBatch: number; maxJSONDepth: number; maxRecords: number } };
export type Progress = (message: string) => void;
